spring.application.name=multiservicio

spring.datasource.url=jdbc:mysql://localhost:3306/multiservicio_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.jpa.properties.jakarta.persistence.schema-generation.database.action=none
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=none

# Evita que DevTools recargue con config antigua de validación
spring.devtools.restart.enabled=true

server.port=8080

jwt.secret=MultiservicioSecretKey2026ParaJWTCon256BitsMinimoRequerido!!
jwt.expiration=86400000